[template]
src = "production.tmpl"
dest = "public/env-config.js"
keys = [
  "/configuration/ui/language",
  "/configuration/api/url",
  "/configuration/map/center",
  "/configuration/map/zoom",
  "/configuration/logger/level"
]
